{
  "hash": "ac6890c0e1ac38f9daed96254d57f6c6",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Chapter: A Historical Timeline of Linear Algebra\"\nsubtitle: \"People, Problems, Ideas, Algorithms, and Applications\"\nauthor: \"He Wang\"\ndate: \"2026-06-01\"\nformat:\n  html:\n    toc: true\n    number-sections: true\n    code-fold: true\n    code-tools: true\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n# The Historical Story of Linear Algebra\n\nLinear algebra did not begin as an abstract theory of vector spaces. It began with a practical problem:\n\n> **How do we solve many equations with many unknowns?**\n\nOver more than two thousand years, this practical question became a language for geometry, mechanics, computation, statistics, optimization, signal processing, machine learning, and artificial intelligence.\n\nThis chapter gives a historical timeline of the major ideas in linear algebra. The goal is not to memorize dates, but to see how the subject grew from **equations** to **transformations**, from **coordinates** to **spaces**, from **matrices** to **algorithms**, and finally from **finite-dimensional vectors** to **modern data and AI**.\n\n---\n\n# 1. How to Read This Chapter\n\nThis chapter is organized in three layers.\n\n1. **Timeline layer:** important years, people, and ideas.\n2. **Mathematical layer:** what each historical idea means in modern notation.\n3. **Application layer:** why the idea matters today in computation, data science, and AI.\n\nThe main storyline is:\n\n$$\n\\text{Equations}\n\\rightarrow\n\\text{Determinants}\n\\rightarrow\n\\text{Matrices}\n\\rightarrow\n\\text{Vector Spaces}\n\\rightarrow\n\\text{Transformations}\n\\rightarrow\n\\text{Spectral Theory}\n\\rightarrow\n\\text{Algorithms}\n\\rightarrow\n\\text{Data and AI}.\n$$\n\n---\n\n# 2. Master Timeline of Linear Algebra\n\n| Year / Period | Mathematician(s) / Source | Historical Development | Linear Algebra Idea | Wikipedia Link |\n|---:|---|---|---|---|\n| c. 1800 BCE | Old Babylonian mathematics | Early algebraic problems involving unknown quantities | Proto-linear equations | [Babylonian mathematics](https://en.wikipedia.org/wiki/Babylonian_mathematics) |\n| c. 200 BCE--200 CE | *The Nine Chapters on the Mathematical Art* | Rod-table methods for systems of equations | Elimination | [The Nine Chapters](https://en.wikipedia.org/wiki/The_Nine_Chapters_on_the_Mathematical_Art) |\n| 1545 | Gerolamo Cardano | Determinant-like expressions for solving two linear equations | Early determinants | [Gerolamo Cardano](https://en.wikipedia.org/wiki/Gerolamo_Cardano) |\n| 1683 | Seki Takakazu | Independent Japanese development of determinants | Determinants | [Seki Takakazu](https://en.wikipedia.org/wiki/Seki_Takakazu) |\n| 1693 | Gottfried Wilhelm Leibniz | Determinant-like symbolic formulas | Determinants and symbolic algebra | [Leibniz](https://en.wikipedia.org/wiki/Gottfried_Wilhelm_Leibniz) |\n| 1750 | Gabriel Cramer | Published Cramer's rule | Linear systems and determinants | [Gabriel Cramer](https://en.wikipedia.org/wiki/Gabriel_Cramer) |\n| 1770s | Alexandre-Théophile Vandermonde, Joseph-Louis Lagrange, Pierre-Simon Laplace | Development of determinant expansions and elimination ideas | Determinant theory | [Vandermonde](https://en.wikipedia.org/wiki/Alexandre-Th%C3%A9ophile_Vandermonde), [Lagrange](https://en.wikipedia.org/wiki/Joseph-Louis_Lagrange), [Laplace](https://en.wikipedia.org/wiki/Pierre-Simon_Laplace) |\n| 1795--1809 | Carl Friedrich Gauss | Systematic elimination in least squares and astronomy | Gaussian elimination, least squares | [Gauss](https://en.wikipedia.org/wiki/Carl_Friedrich_Gauss) |\n| 1822 | Joseph Fourier | *Théorie analytique de la chaleur* | Fourier series and transform | [Joseph Fourier](https://en.wikipedia.org/wiki/Joseph_Fourier) |\n| 1827--1829 | Augustin-Louis Cauchy | Work on determinants, eigenvalue-type ideas, and symmetric forms | Determinants, quadratic forms | [Cauchy](https://en.wikipedia.org/wiki/Augustin-Louis_Cauchy) |\n| 1843 | William Rowan Hamilton | Quaternions | Vectors, rotations, noncommutative algebra | [Hamilton](https://en.wikipedia.org/wiki/William_Rowan_Hamilton) |\n| 1844 | Hermann Grassmann | *Ausdehnungslehre* | Vector spaces, exterior algebra | [Grassmann](https://en.wikipedia.org/wiki/Hermann_Grassmann) |\n| 1848 | James Joseph Sylvester | Introduced the term \"matrix\" | Matrix terminology | [Sylvester](https://en.wikipedia.org/wiki/James_Joseph_Sylvester) |\n| 1850s | Arthur Cayley | Matrix algebra, matrix multiplication, inverse matrices | Matrices as algebraic objects | [Arthur Cayley](https://en.wikipedia.org/wiki/Arthur_Cayley) |\n| 1870 | Camille Jordan | Canonical forms | Jordan form | [Camille Jordan](https://en.wikipedia.org/wiki/Camille_Jordan) |\n| 1878--1890s | Ferdinand Georg Frobenius | Matrix theory and linear transformations | Eigenvalues, canonical forms | [Frobenius](https://en.wikipedia.org/wiki/Ferdinand_Georg_Frobenius) |\n| 1900--1910 | David Hilbert, Erhard Schmidt, Frigyes Riesz | Infinite-dimensional inner product spaces | Hilbert spaces | [Hilbert space](https://en.wikipedia.org/wiki/Hilbert_space) |\n| 1901 | Karl Pearson | Principal axes in statistics | PCA roots | [Karl Pearson](https://en.wikipedia.org/wiki/Karl_Pearson) |\n| 1909 | Issai Schur | Schur decomposition | Unitary triangularization | [Issai Schur](https://en.wikipedia.org/wiki/Issai_Schur) |\n| 1910 | Alfréd Haar | Haar system | Haar basis and wavelets | [Haar wavelet](https://en.wikipedia.org/wiki/Haar_wavelet) |\n| 1925--1930 | Werner Heisenberg, John von Neumann, Paul Dirac | Quantum mechanics uses operators on Hilbert spaces | Linear operators, spectra | [Matrix mechanics](https://en.wikipedia.org/wiki/Matrix_mechanics), [Von Neumann](https://en.wikipedia.org/wiki/John_von_Neumann) |\n| 1933 | Harold Hotelling | Principal component analysis | Eigenvectors of covariance matrices | [PCA](https://en.wikipedia.org/wiki/Principal_component_analysis) |\n| 1936 | Carl Eckart and Gale Young | Best low-rank approximation theorem | SVD and approximation | [Eckart--Young theorem](https://en.wikipedia.org/wiki/Low-rank_approximation#Basic_low-rank_approximation_problem) |\n| 1946--1950s | Early electronic computers | Large-scale numerical matrix computation | Numerical linear algebra | [ENIAC](https://en.wikipedia.org/wiki/ENIAC) |\n| 1950s | Magnus Hestenes, Eduard Stiefel | Conjugate gradient method | Iterative linear solvers | [Conjugate gradient method](https://en.wikipedia.org/wiki/Conjugate_gradient_method) |\n| 1958 | Alston Householder | Householder transformations | Orthogonal transformations | [Householder transformation](https://en.wikipedia.org/wiki/Householder_transformation) |\n| 1961--1962 | John G. F. Francis, Vera Kublanovskaya | QR algorithm | Eigenvalue computation | [QR algorithm](https://en.wikipedia.org/wiki/QR_algorithm) |\n| 1965 | James Cooley and John Tukey | Popularization of FFT | Fast Fourier transform | [Fast Fourier transform](https://en.wikipedia.org/wiki/Fast_Fourier_transform) |\n| 1970s | Gene Golub, Charles Van Loan, James Wilkinson | Modern numerical linear algebra | Stability and algorithms | [Gene Golub](https://en.wikipedia.org/wiki/Gene_H._Golub), [James H. Wilkinson](https://en.wikipedia.org/wiki/James_H._Wilkinson) |\n| 1980s--1990s | Wavelet community: Ingrid Daubechies, Stéphane Mallat, Yves Meyer | Modern wavelet theory | Multiresolution analysis | [Ingrid Daubechies](https://en.wikipedia.org/wiki/Ingrid_Daubechies), [Wavelet](https://en.wikipedia.org/wiki/Wavelet) |\n| 1998 | Larry Page, Sergey Brin | PageRank | Eigenvectors of large graphs | [PageRank](https://en.wikipedia.org/wiki/PageRank) |\n| 2000s | Large-scale data science | Matrix factorization and PCA become standard tools | SVD, sparse matrices, optimization | [Matrix factorization](https://en.wikipedia.org/wiki/Matrix_factorization_(recommender_systems)) |\n| 2010s--present | Deep learning and generative AI | High-dimensional vectors, tensors, gradients | Linear algebra for AI | [Deep learning](https://en.wikipedia.org/wiki/Deep_learning), [Tensor](https://en.wikipedia.org/wiki/Tensor) |\n\n---\n\n# 3. Ancient and Early Algebra: Solving Many Equations\n\nLinear algebra begins with systems of equations. In modern notation, a system such as\n\n$$\n\\begin{aligned}\n2x+3y-z &= 5,\\\\\nx-y+4z &= 2,\\\\\n3x+2y+z &= 7\n\\end{aligned}\n$$\n\nis written as\n\n$$\nAx=b.\n$$\n\nBut historically, the matrix notation came much later. Ancient mathematicians worked directly with organized tables of numbers.\n\n## 3.1 The Nine Chapters and Elimination\n\nThe Chinese text *The Nine Chapters on the Mathematical Art* contains procedures that are very close to what we now call Gaussian elimination.\n\nModern row operations are:\n\n1. swap two rows;\n2. multiply a row by a nonzero scalar;\n3. add a multiple of one row to another row.\n\nThese operations do not change the solution set.\n\nIn matrix form:\n\n$$\n\\left[\n\\begin{array}{ccc|c}\n2 & 3 & -1 & 5\\\\\n1 & -1 & 4 & 2\\\\\n3 & 2 & 1 & 7\n\\end{array}\n\\right]\n\\quad \\longrightarrow \\quad\n\\text{row echelon form}.\n$$\n\n::: {.callout-note}\n## Historical lesson\n\nLinear algebra began as an algorithm. The earliest form of linear algebra was not a theorem about vector spaces, but a procedure for reducing equations.\n:::\n\n---\n\n# 4. Determinants: The First Great Invariant\n\nBefore matrices became objects in their own right, determinants were already studied.\n\nFor a $2\\times 2$ matrix\n\n$$\nA=\n\\begin{bmatrix}\na & b\\\\\nc & d\n\\end{bmatrix},\n$$\n\nthe determinant is\n\n$$\n\\det(A)=ad-bc.\n$$\n\nFor a $3\\times 3$ matrix,\n\n$$\nA=\n\\begin{bmatrix}\na & b & c\\\\\nd & e & f\\\\\ng & h & i\n\\end{bmatrix},\n$$\n\n$$\n\\det(A)=aei+bfg+cdh-ceg-bdi-afh.\n$$\n\n## 4.1 Mathematicians and Years\n\n| Year | Mathematician | Contribution |\n|---:|---|---|\n| 1545 | [Cardano](https://en.wikipedia.org/wiki/Gerolamo_Cardano) | Determinant-like expressions for small systems |\n| 1683 | [Seki Takakazu](https://en.wikipedia.org/wiki/Seki_Takakazu) | Independent determinant theory in Japan |\n| 1693 | [Leibniz](https://en.wikipedia.org/wiki/Gottfried_Wilhelm_Leibniz) | Determinant-like symbolic formulas in Europe |\n| 1750 | [Cramer](https://en.wikipedia.org/wiki/Gabriel_Cramer) | Cramer's rule |\n| 1771 | [Vandermonde](https://en.wikipedia.org/wiki/Alexandre-Th%C3%A9ophile_Vandermonde) | Determinants as functions |\n| 1772--1773 | [Laplace](https://en.wikipedia.org/wiki/Pierre-Simon_Laplace), [Lagrange](https://en.wikipedia.org/wiki/Joseph-Louis_Lagrange) | Expansion formulas and elimination |\n| 1812 | [Cauchy](https://en.wikipedia.org/wiki/Augustin-Louis_Cauchy) | Systematic determinant theory |\n\n## 4.2 Algebraic Meaning\n\nA square matrix $A$ is invertible if and only if\n\n$$\n\\det(A)\\ne 0.\n$$\n\nThus, determinants determine whether the linear system\n\n$$\nAx=b\n$$\n\nhas a unique solution for every $b$.\n\n## 4.3 Geometric Meaning\n\nThe absolute value $|\\det(A)|$ measures volume scaling:\n\n$$\n\\text{volume of }A(S)=|\\det(A)|\\cdot \\text{volume of }S.\n$$\n\nSo determinants connect algebra and geometry.\n\n## 4.4 Multilinear Meaning\n\nThe determinant is an alternating multilinear function of the columns of $A$. If two columns are equal, then\n\n$$\n\\det(A)=0.\n$$\n\nThis is the historical bridge from determinants to exterior algebra.\n\n---\n\n# 5. Gauss, Least Squares, and Elimination\n\n[Carl Friedrich Gauss](https://en.wikipedia.org/wiki/Carl_Friedrich_Gauss) used systematic elimination methods in astronomical computations. His work on least squares was motivated by the need to estimate orbits from imperfect observations.\n\nThe least-squares problem is:\n\n$$\n\\min_x \\|Ax-b\\|^2.\n$$\n\nThe normal equations are:\n\n$$\nA^TAx=A^Tb.\n$$\n\n## 5.1 Historical Interpretation\n\nThis is a turning point:\n\n| Earlier Problem | Gauss's Broader Problem |\n|---|---|\n| Solve exactly $Ax=b$ | Solve approximately when data are noisy |\n| Algebraic equations | Measurement and error |\n| Exact answer | Best approximation |\n\nLeast squares introduces one of the most important ideas in applied linear algebra:\n\n> When exact solution is impossible, find the best projection.\n\n---\n\n# 6. Fourier: Functions as Infinite Vectors\n\nIn 1822, [Joseph Fourier](https://en.wikipedia.org/wiki/Joseph_Fourier) published his work on heat flow. He proposed that complicated periodic functions could be decomposed into simple waves.\n\nA Fourier series has the form\n\n$$\nf(x)=\\frac{a_0}{2}+\\sum_{k=1}^{\\infty}\n\\left(a_k\\cos(kx)+b_k\\sin(kx)\\right).\n$$\n\n## 6.1 Linear Algebra Meaning\n\nThe functions\n\n$$\n1,\\cos x,\\sin x,\\cos 2x,\\sin 2x,\\ldots\n$$\n\nact like an orthogonal basis.\n\nThe Fourier coefficient is a coordinate:\n\n$$\na_k=\\frac{1}{\\pi}\\int_{-\\pi}^{\\pi} f(x)\\cos(kx)\\,dx.\n$$\n\nThus Fourier analysis is infinite-dimensional linear algebra.\n\n## 6.2 Why This Was Revolutionary\n\nFourier's idea connected:\n\n- heat equation,\n- differential equations,\n- orthogonality,\n- projections,\n- basis expansions,\n- signal processing,\n- Hilbert spaces.\n\nThe modern [Fourier transform](https://en.wikipedia.org/wiki/Fourier_transform) extends this idea to nonperiodic functions.\n\n---\n\n# 7. Hamilton, Grassmann, and the Birth of Abstract Vectors\n\n## 7.1 Hamilton and Quaternions\n\nIn 1843, [William Rowan Hamilton](https://en.wikipedia.org/wiki/William_Rowan_Hamilton) discovered quaternions. Quaternions were invented to describe rotations in space.\n\nA quaternion has the form\n\n$$\na+bi+cj+dk.\n$$\n\nQuaternions are not ordinary vector spaces alone; they also have a multiplication rule. But they helped mathematicians think beyond ordinary real numbers.\n\n## 7.2 Grassmann and Extension Theory\n\nIn 1844, [Hermann Grassmann](https://en.wikipedia.org/wiki/Hermann_Grassmann) published *Ausdehnungslehre*, or \"Theory of Extension.\"\n\nGrassmann's work anticipated:\n\n- vector spaces,\n- subspaces,\n- linear independence,\n- exterior products,\n- oriented area and volume.\n\nThe wedge product\n\n$$\nu\\wedge v\n$$\n\nrepresents an oriented area element.\n\n## 7.3 Historical Importance\n\nGrassmann's ideas were too abstract for many readers of his time. But later they became central to modern linear algebra, differential geometry, topology, and physics.\n\n---\n\n# 8. Sylvester and Cayley: Matrices Become Objects\n\nThe word **matrix** was introduced by [James Joseph Sylvester](https://en.wikipedia.org/wiki/James_Joseph_Sylvester) in 1848.\n\nThen [Arthur Cayley](https://en.wikipedia.org/wiki/Arthur_Cayley) developed matrix algebra in the 1850s. Cayley treated matrices not just as arrays of coefficients, but as mathematical objects that could be added, multiplied, and inverted.\n\n## 8.1 Matrix Multiplication\n\nIf\n\n$$\nA\\in \\mathbb{R}^{m\\times n},\\qquad B\\in \\mathbb{R}^{n\\times p},\n$$\n\nthen\n\n$$\nAB\\in \\mathbb{R}^{m\\times p}.\n$$\n\nMatrix multiplication represents composition of linear maps:\n\n$$\nA(Bx)=(AB)x.\n$$\n\n## 8.2 Historical Shift\n\nBefore Cayley:\n\n$$\n\\text{matrices were coefficient tables.}\n$$\n\nAfter Cayley:\n\n$$\n\\text{matrices became algebraic objects and transformations.}\n$$\n\nThis is one of the central conceptual shifts in the subject.\n\n---\n\n# 9. Vector Spaces: The Language of Modern Linear Algebra\n\nA vector space is a set where vectors can be added and scaled.\n\nExamples:\n\n$$\n\\mathbb{R}^n,\\qquad\nP_n=\\{\\text{polynomials of degree at most }n\\},\\qquad\nC[a,b],\\qquad\n\\mathbb{R}^{m\\times n}.\n$$\n\nThe abstract definition of vector spaces developed gradually in the nineteenth and early twentieth centuries.\n\nImportant contributors include:\n\n- [Hermann Grassmann](https://en.wikipedia.org/wiki/Hermann_Grassmann),\n- [Giuseppe Peano](https://en.wikipedia.org/wiki/Giuseppe_Peano),\n- [David Hilbert](https://en.wikipedia.org/wiki/David_Hilbert),\n- [Stefan Banach](https://en.wikipedia.org/wiki/Stefan_Banach).\n\n## 9.1 Basis and Dimension\n\nA basis $\\mathcal{B}=\\{v_1,\\ldots,v_n\\}$ allows every vector $v\\in V$ to be written uniquely as\n\n$$\nv=c_1v_1+\\cdots+c_nv_n.\n$$\n\nThe number of basis vectors is the dimension.\n\n## 9.2 A Basis Is a Language\n\nDifferent bases describe the same object in different languages.\n\n| Basis | Historical / Modern Use |\n|---|---|\n| Standard basis | Coordinates |\n| Eigenbasis | Dynamics and diagonalization |\n| Orthogonal basis | Projection and least squares |\n| Fourier basis | Frequency decomposition |\n| Haar basis | Multiscale decomposition |\n| Singular vectors | Low-rank data representation |\n\n---\n\n# 10. Cauchy, Jordan, Frobenius: Eigenvalues and Canonical Forms\n\nEigenvalues answer the question:\n\n> Which directions are preserved by a linear transformation?\n\nA nonzero vector $v$ is an eigenvector of $A$ if\n\n$$\nAv=\\lambda v.\n$$\n\n## 10.1 Important Mathematicians\n\n| Mathematician | Years | Contribution |\n|---|---:|---|\n| [Augustin-Louis Cauchy](https://en.wikipedia.org/wiki/Augustin-Louis_Cauchy) | 1789--1857 | Determinants, symmetric forms, early spectral ideas |\n| [Camille Jordan](https://en.wikipedia.org/wiki/Camille_Jordan) | 1838--1922 | Jordan canonical form |\n| [Ferdinand Georg Frobenius](https://en.wikipedia.org/wiki/Ferdinand_Georg_Frobenius) | 1849--1917 | Matrix theory, Perron--Frobenius theory |\n| [Oskar Perron](https://en.wikipedia.org/wiki/Oskar_Perron) | 1880--1975 | Positive matrices |\n| [Issai Schur](https://en.wikipedia.org/wiki/Issai_Schur) | 1875--1941 | Schur decomposition |\n\n## 10.2 Jordan Form\n\nThe Jordan form says that, over the complex numbers, every square matrix can be put into a nearly diagonal form:\n\n$$\nA=PJP^{-1}.\n$$\n\nThis is powerful in theory but often unstable numerically.\n\n## 10.3 Perron--Frobenius Theory\n\nFor matrices with positive entries, the Perron--Frobenius theorem gives a dominant positive eigenvalue and positive eigenvector.\n\nThis appears in:\n\n- Markov chains,\n- population models,\n- network centrality,\n- PageRank.\n\n---\n\n# 11. Symmetric Matrices and the Spectral Theorem\n\nA real matrix $A$ is symmetric if\n\n$$\nA^T=A.\n$$\n\nThe spectral theorem states that a real symmetric matrix can be orthogonally diagonalized:\n\n$$\nA=QDQ^T.\n$$\n\nHere $Q$ is orthogonal and $D$ is diagonal.\n\n## 11.1 Historical Meaning\n\nSymmetric matrices arise naturally from:\n\n- quadratic forms,\n- mechanics,\n- energy,\n- covariance matrices,\n- optimization,\n- geometry.\n\n## 11.2 Quadratic Forms\n\nA symmetric matrix defines\n\n$$\nq(x)=x^TAx.\n$$\n\nUsing the spectral theorem,\n\n$$\nq(x)=\\lambda_1y_1^2+\\cdots+\\lambda_ny_n^2.\n$$\n\nThus eigenvalues classify the shape:\n\n| Eigenvalues | Shape |\n|---|---|\n| all positive | positive definite bowl |\n| all nonnegative | positive semidefinite surface |\n| mixed signs | saddle |\n| all negative | negative definite bowl |\n\n---\n\n# 12. Schur Decomposition: Stable Triangularization\n\n[Issai Schur](https://en.wikipedia.org/wiki/Issai_Schur) introduced a decomposition that is central in modern numerical linear algebra.\n\nEvery complex square matrix can be written as\n\n$$\nA=UTU^*,\n$$\n\nwhere $U$ is unitary and $T$ is upper triangular.\n\n## 12.1 Why Schur Decomposition Matters\n\nThe Jordan form is elegant but unstable for computation. Schur decomposition is stable and works well numerically.\n\nIt supports:\n\n- eigenvalue algorithms,\n- matrix functions,\n- stability analysis,\n- numerical spectral theory.\n\nA useful slogan is:\n\n> Anything the Jordan form can do theoretically, the Schur form can often do better numerically.\n\n---\n\n# 13. Hilbert Spaces: Infinite-Dimensional Geometry\n\nA Hilbert space is a complete inner product space.\n\nImportant contributors include:\n\n- [David Hilbert](https://en.wikipedia.org/wiki/David_Hilbert),\n- [Erhard Schmidt](https://en.wikipedia.org/wiki/Erhard_Schmidt),\n- [Frigyes Riesz](https://en.wikipedia.org/wiki/Frigyes_Riesz),\n- [John von Neumann](https://en.wikipedia.org/wiki/John_von_Neumann).\n\n## 13.1 Definition\n\nA Hilbert space $\\mathcal{H}$ has an inner product\n\n$$\n\\langle f,g\\rangle\n$$\n\nand every Cauchy sequence converges inside the space.\n\nExamples include:\n\n$$\n\\mathbb{R}^n,\n\\qquad\n\\ell^2,\n\\qquad\nL^2[a,b].\n$$\n\n## 13.2 Orthogonal Projection Theorem\n\nIf $M$ is a closed subspace of a Hilbert space and $y\\in \\mathcal{H}$, then there exists a unique projection\n\n$$\n\\operatorname{Proj}_M(y)\\in M\n$$\n\nsuch that\n\n$$\ny-\\operatorname{Proj}_M(y)\n$$\n\nis orthogonal to $M$.\n\nThis is the infinite-dimensional version of least squares.\n\n## 13.3 Applications\n\nHilbert spaces are central in:\n\n- Fourier analysis,\n- PDEs,\n- quantum mechanics,\n- probability,\n- signal processing,\n- kernel methods in machine learning.\n\n---\n\n# 14. Quantum Mechanics: Matrices Become Observables\n\nIn the 1920s, quantum mechanics gave linear algebra a new physical meaning.\n\nImportant figures:\n\n- [Werner Heisenberg](https://en.wikipedia.org/wiki/Werner_Heisenberg),\n- [Max Born](https://en.wikipedia.org/wiki/Max_Born),\n- [Pascual Jordan](https://en.wikipedia.org/wiki/Pascual_Jordan),\n- [John von Neumann](https://en.wikipedia.org/wiki/John_von_Neumann),\n- [Paul Dirac](https://en.wikipedia.org/wiki/Paul_Dirac).\n\nIn quantum mechanics:\n\n- states are vectors,\n- observables are operators,\n- measurement outcomes are eigenvalues,\n- probabilities come from inner products.\n\nThe equation\n\n$$\nA\\psi=\\lambda\\psi\n$$\n\nhas a physical interpretation: $\\lambda$ is a possible measured value.\n\n---\n\n# 15. PCA: Statistics Meets Eigenvectors\n\nPrincipal component analysis grew from statistical work by [Karl Pearson](https://en.wikipedia.org/wiki/Karl_Pearson) and [Harold Hotelling](https://en.wikipedia.org/wiki/Harold_Hotelling).\n\nGiven centered data matrix $X$, the covariance matrix is\n\n$$\nC=\\frac{1}{N-1}X^TX.\n$$\n\nPCA finds eigenvectors of $C$:\n\n$$\nCv_i=\\lambda_i v_i.\n$$\n\nThe eigenvectors $v_i$ are directions of maximal variance.\n\n## 15.1 Modern Meaning\n\nPCA is used for:\n\n- dimension reduction,\n- data visualization,\n- noise reduction,\n- feature extraction,\n- exploratory data analysis.\n\n---\n\n# 16. SVD: The Universal Matrix Decomposition\n\nThe singular value decomposition states that every real matrix $X\\in\\mathbb{R}^{m\\times n}$ can be written as\n\n$$\nX=U\\Sigma V^T.\n$$\n\nThe singular values are nonnegative:\n\n$$\n\\sigma_1\\geq \\sigma_2\\geq \\cdots \\geq 0.\n$$\n\n## 16.1 Historical Milestones\n\n| Year | People | Contribution |\n|---:|---|---|\n| 1870s--1900s | Beltrami, Jordan, Sylvester, Schmidt | Early singular value ideas |\n| 1936 | [Carl Eckart](https://en.wikipedia.org/wiki/Carl_Eckart), [Gale Young](https://en.wikipedia.org/wiki/Gale_Young) | Best low-rank approximation |\n| 1960s--1970s | [Gene Golub](https://en.wikipedia.org/wiki/Gene_H._Golub), William Kahan, Christian Reinsch | Stable numerical algorithms for SVD |\n\n## 16.2 Rank-One Expansion\n\n$$\nX=\\sigma_1u_1v_1^T+\\cdots+\\sigma_ru_rv_r^T.\n$$\n\nThe best rank-$k$ approximation is\n\n$$\nX_k=\\sigma_1u_1v_1^T+\\cdots+\\sigma_ku_kv_k^T.\n$$\n\n## 16.3 Applications\n\nSVD is used in:\n\n- image compression,\n- pseudoinverse,\n- least squares,\n- PCA,\n- recommendation systems,\n- low-rank approximation,\n- latent semantic analysis,\n- numerical rank detection.\n\n---\n\n# 17. Haar, Wavelets, and Multiresolution\n\nIn 1910, [Alfréd Haar](https://en.wikipedia.org/wiki/Alfr%C3%A9d_Haar) introduced what is now called the Haar system.\n\nA Haar basis for $\\mathbb{R}^4$ is\n\n$$\nw_1=\n\\begin{bmatrix}\n1\\\\1\\\\1\\\\1\n\\end{bmatrix},\n\\quad\nw_2=\n\\begin{bmatrix}\n1\\\\1\\\\-1\\\\-1\n\\end{bmatrix},\n\\quad\nw_3=\n\\begin{bmatrix}\n1\\\\-1\\\\0\\\\0\n\\end{bmatrix},\n\\quad\nw_4=\n\\begin{bmatrix}\n0\\\\0\\\\1\\\\-1\n\\end{bmatrix}.\n$$\n\n## 17.1 Meaning of Haar Coefficients\n\nFor a signal $v=(v_1,v_2,v_3,v_4)^T$,\n\n$$\nc_1=\\frac{v_1+v_2+v_3+v_4}{4}\n$$\n\ncaptures the average.\n\nOther coefficients capture coarse and fine differences.\n\n## 17.2 Modern Wavelet Theory\n\nLater mathematicians, including [Yves Meyer](https://en.wikipedia.org/wiki/Yves_Meyer), [Stéphane Mallat](https://en.wikipedia.org/wiki/St%C3%A9phane_Mallat), and [Ingrid Daubechies](https://en.wikipedia.org/wiki/Ingrid_Daubechies), developed modern wavelet theory.\n\nWavelets are used in:\n\n- image compression,\n- denoising,\n- edge detection,\n- numerical PDEs,\n- signal processing.\n\n---\n\n# 18. FFT: The Fast Algorithm Era\n\nThe [Fast Fourier Transform](https://en.wikipedia.org/wiki/Fast_Fourier_transform) computes the discrete Fourier transform efficiently.\n\nThe discrete Fourier transform of a vector $x=(x_0,\\ldots,x_{n-1})$ is\n\n$$\nX_k=\\sum_{j=0}^{n-1}x_j e^{-2\\pi i jk/n}.\n$$\n\nDirect computation costs $O(n^2)$.\n\nThe FFT reduces this to\n\n$$\nO(n\\log n).\n$$\n\n## 18.1 Important Names\n\n| Person | Role |\n|---|---|\n| [Carl Friedrich Gauss](https://en.wikipedia.org/wiki/Carl_Friedrich_Gauss) | Early related ideas in interpolation and computation |\n| [James Cooley](https://en.wikipedia.org/wiki/James_Cooley) | Cooley--Tukey FFT algorithm |\n| [John Tukey](https://en.wikipedia.org/wiki/John_Tukey) | Cooley--Tukey FFT algorithm |\n\n## 18.2 Why FFT Matters\n\nFFT made Fourier analysis practical at scale.\n\nApplications include:\n\n- audio processing,\n- image processing,\n- solving PDEs,\n- convolution,\n- filtering,\n- radar,\n- medical imaging.\n\n---\n\n# 19. Numerical Linear Algebra: Stability and Algorithms\n\nModern linear algebra is not only about whether a formula is true. It is also about whether an algorithm is fast and stable.\n\nImportant contributors include:\n\n- [James H. Wilkinson](https://en.wikipedia.org/wiki/James_H._Wilkinson),\n- [Gene H. Golub](https://en.wikipedia.org/wiki/Gene_H._Golub),\n- [Charles F. Van Loan](https://en.wikipedia.org/wiki/Charles_F._Van_Loan),\n- [Alston Householder](https://en.wikipedia.org/wiki/Alston_Scott_Householder),\n- [Wallace Givens](https://en.wikipedia.org/wiki/Wallace_Givens).\n\n## 19.1 QR Algorithm\n\nThe QR algorithm was developed independently by [John G. F. Francis](https://en.wikipedia.org/wiki/John_G._F._Francis) and [Vera Kublanovskaya](https://en.wikipedia.org/wiki/Vera_Kublanovskaya).\n\nGiven\n\n$$\nA_k=Q_kR_k,\n$$\n\ndefine\n\n$$\nA_{k+1}=R_kQ_k.\n$$\n\nRepeated iteration reveals eigenvalue information and leads toward Schur form.\n\n## 19.2 Householder and Givens Transformations\n\nHouseholder reflections and Givens rotations are stable orthogonal transformations used to compute QR decompositions.\n\nThey preserve length:\n\n$$\n\\|Qx\\|=\\|x\\|.\n$$\n\nThis is why orthogonal transformations are numerically safe.\n\n---\n\n# 20. Sparse Matrices and Complexity\n\nLarge-scale linear algebra requires attention to memory and time.\n\nFor a dense matrix $A\\in\\mathbb{R}^{m\\times n}$, memory cost is\n\n$$\nO(mn).\n$$\n\nFor matrix-vector multiplication,\n\n$$\nAx,\n$$\n\nthe cost is\n\n$$\nO(mn).\n$$\n\nFor matrix multiplication,\n\n$$\nAB,\\qquad A\\in\\mathbb{R}^{m\\times n},\\quad B\\in\\mathbb{R}^{n\\times p},\n$$\n\nthe classical cost is\n\n$$\nO(mnp).\n$$\n\n## 20.1 Sparse Matrix Idea\n\nIf most entries are zero, we should store only nonzero entries.\n\nThis is essential for:\n\n- graph algorithms,\n- finite element methods,\n- PDE solvers,\n- recommender systems,\n- web search,\n- large neural networks.\n\n## 20.2 A Historical Shift\n\nClassical mathematics asked:\n\n> What is the formula?\n\nNumerical linear algebra asks:\n\n> What is the stable and efficient algorithm?\n\n---\n\n# 21. Grassmannians: Subspaces as Points\n\nThe [Grassmannian](https://en.wikipedia.org/wiki/Grassmannian)\n\n$$\n\\operatorname{Gr}(k,n)\n$$\n\nis the set of all $k$-dimensional subspaces of $\\mathbb{R}^n$.\n\nThis idea is named after [Hermann Grassmann](https://en.wikipedia.org/wiki/Hermann_Grassmann).\n\n## 21.1 Principal Angles\n\nGiven two subspaces $U$ and $W$, their principal angles\n\n$$\n\\theta_1,\\ldots,\\theta_k\n$$\n\nmeasure how far the subspaces are from each other.\n\nThey can be computed using QR and SVD.\n\n## 21.2 Applications\n\nGrassmannian geometry appears in:\n\n- computer vision,\n- subspace clustering,\n- reduced-order modeling,\n- signal processing,\n- machine learning on subspaces.\n\n---\n\n# 22. Multilinear Algebra and Tensors\n\nMultilinear algebra generalizes linear algebra to several vector inputs.\n\nImportant objects:\n\n- tensor product,\n- exterior product,\n- determinant,\n- bilinear forms,\n- multilinear maps.\n\n## 22.1 Tensor Products\n\nFor vector spaces $V$ and $W$, the tensor product is\n\n$$\nV\\otimes W.\n$$\n\nIf\n\n$$\nv\\in \\mathbb{R}^m,\\qquad w\\in \\mathbb{R}^n,\n$$\n\nthen\n\n$$\nv\\otimes w\n$$\n\ncan be represented as an $m\\times n$ matrix.\n\n## 22.2 Exterior Products\n\nThe exterior product\n\n$$\nv_1\\wedge v_2\\wedge \\cdots \\wedge v_k\n$$\n\nrepresents oriented $k$-dimensional volume.\n\nThis connects linear algebra to:\n\n- determinants,\n- differential forms,\n- geometry,\n- topology,\n- physics.\n\n## 22.3 Tensors in AI\n\nModern AI uses tensors as multidimensional arrays:\n\n$$\n\\text{image} \\sim \\text{height}\\times \\text{width}\\times \\text{channels},\n$$\n\n$$\n\\text{video} \\sim \\text{time}\\times \\text{height}\\times \\text{width}\\times \\text{channels}.\n$$\n\nThus tensor algebra is not only abstract. It is a practical language for modern data.\n\n---\n\n# 23. PageRank and Network Linear Algebra\n\nIn the late 1990s, [Larry Page](https://en.wikipedia.org/wiki/Larry_Page) and [Sergey Brin](https://en.wikipedia.org/wiki/Sergey_Brin) developed PageRank.\n\nPageRank is based on an eigenvector problem.\n\nIf $P$ is a transition matrix of the web graph, PageRank seeks a vector $r$ such that\n\n$$\nPr=r.\n$$\n\nThis means $r$ is an eigenvector with eigenvalue $1$.\n\n## 23.1 Historical Meaning\n\nThis is a modern example of an old idea:\n\n$$\n\\text{eigenvectors}\n\\quad \\longrightarrow \\quad\n\\text{importance in a network}.\n$$\n\nEigenvectors are not only hidden directions in geometry; they can also measure centrality in graphs.\n\n---\n\n# 24. Linear Algebra in Optimization\n\nOptimization uses linear algebra at every step.\n\nFor a quadratic function\n\n$$\nf(x)=\\frac12 x^TAx-b^Tx,\n$$\n\nthe gradient is\n\n$$\n\\nabla f(x)=Ax-b.\n$$\n\nThe Hessian is\n\n$$\n\\nabla^2f(x)=A.\n$$\n\nIf $A$ is positive definite, then $f$ is convex and has a unique minimizer.\n\n## 24.1 Eigenvalues and Conditioning\n\nThe condition number\n\n$$\n\\kappa(A)=\\frac{\\lambda_{\\max}(A)}{\\lambda_{\\min}(A)}\n$$\n\ncontrols how difficult the optimization problem is.\n\nLarge condition number means slow convergence for many algorithms.\n\n---\n\n# 25. Linear Algebra in Machine Learning and AI\n\nModern AI is built from linear algebraic objects.\n\n| AI Object | Linear Algebra Interpretation |\n|---|---|\n| Data point | Vector |\n| Data set | Matrix |\n| Image | Tensor |\n| Word embedding | High-dimensional vector |\n| Neural network layer | Matrix transformation plus nonlinearity |\n| Attention scores | Matrix products |\n| Training | Gradient-based optimization |\n| Compression | Low-rank approximation |\n| Similarity search | Inner products and distances |\n\nA neural network layer has the form\n\n$$\nh=\\sigma(Wx+b).\n$$\n\nEven when the full model is nonlinear, each layer uses linear transformations.\n\n---\n\n# 26. Topic-by-Topic Historical Map\n\n| Course Topic | Main Historical Names | Key Years | Modern Meaning |\n|---|---|---:|---|\n| Linear systems | Ancient Chinese mathematicians, Gauss | ancient--1800s | Solving constraints |\n| Determinants | Seki, Leibniz, Cramer, Vandermonde, Laplace, Cauchy | 1683--1812 | Invertibility and volume |\n| Matrices | Sylvester, Cayley | 1848--1858 | Transformations |\n| Vector spaces | Grassmann, Peano, Hilbert, Banach | 1844--1930 | Abstract structure |\n| Inner products | Euclid, Fourier, Hilbert | ancient--1900s | Geometry and projection |\n| Eigenvalues | Cauchy, Jordan, Frobenius, Perron, Schur | 1800s--1900s | Hidden directions |\n| Symmetric matrices | Cauchy, Jacobi, Hilbert | 1800s--1900s | Spectral theorem |\n| Schur decomposition | Issai Schur | 1909 | Stable triangularization |\n| SVD | Beltrami, Jordan, Schmidt, Eckart, Young, Golub, Kahan | 1870s--1970s | Data decomposition |\n| Fourier analysis | Fourier, Dirichlet, Riemann, Hilbert | 1822--1900s | Frequency basis |\n| Haar bases | Alfréd Haar | 1910 | Multiscale basis |\n| Wavelets | Meyer, Mallat, Daubechies | 1980s--1990s | Modern signal compression |\n| Hilbert spaces | Hilbert, Schmidt, Riesz, von Neumann | 1900s--1930s | Infinite-dimensional geometry |\n| QR algorithm | Francis, Kublanovskaya | 1961--1962 | Eigenvalue computation |\n| FFT | Cooley, Tukey, Gauss | 1965 | Fast frequency computation |\n| Grassmannians | Grassmann, Plücker | 1800s | Geometry of subspaces |\n| Tensors | Grassmann, Ricci-Curbastro, Levi-Civita | 1800s--1900s | Multidimensional data |\n| Numerical linear algebra | Wilkinson, Golub, Van Loan | 1950s--present | Stable algorithms |\n| Machine learning | Pearson, Hotelling, Vapnik, modern AI researchers | 1901--present | Data and prediction |\n\n---\n\n# 27. A More Detailed Chronological Narrative\n\n## 27.1 Ancient to 1700: Equations Before Matrices\n\nLinear algebra begins with practical arithmetic. People needed to solve problems involving unknown quantities. The idea of eliminating unknowns existed long before matrices were formally defined.\n\nImportant ideas:\n\n$$\n\\text{unknowns},\\quad\n\\text{systems},\\quad\n\\text{tables},\\quad\n\\text{elimination}.\n$$\n\n## 27.2 1700--1800: Determinants and Exact Solutions\n\nThe determinant became the first major invariant of linear systems.\n\nImportant names:\n\n- Seki,\n- Leibniz,\n- Cramer,\n- Vandermonde,\n- Laplace,\n- Lagrange.\n\nThe central question was:\n\n> When does a system have a unique solution?\n\n## 27.3 1800--1850: Approximation, Fourier, and Abstract Directions\n\nGauss pushed linear algebra toward approximation and computation. Fourier pushed it toward functions and infinite series. Hamilton and Grassmann pushed it toward abstract algebra and geometry.\n\nThis period created three major future directions:\n\n$$\n\\text{computation},\\quad\n\\text{function spaces},\\quad\n\\text{abstract vector spaces}.\n$$\n\n## 27.4 1850--1900: Matrices Become Algebra\n\nSylvester named matrices. Cayley developed matrix algebra. Jordan and Frobenius studied canonical forms.\n\nThe matrix became a mathematical object.\n\n## 27.5 1900--1950: Spectral Theory and Hilbert Space\n\nHilbert spaces, functional analysis, quantum mechanics, and PCA all developed during this period.\n\nLinear algebra expanded from finite-dimensional spaces to infinite-dimensional spaces.\n\n## 27.6 1950--1980: Numerical Linear Algebra\n\nComputers made large matrix problems central.\n\nNew questions appeared:\n\n- Is the algorithm stable?\n- How many operations does it take?\n- How much memory does it need?\n- Can it exploit sparsity?\n- Can it work for ill-conditioned matrices?\n\n## 27.7 1980--Present: Data, Networks, and AI\n\nLinear algebra became the core language of data science.\n\nThe main objects are:\n\n$$\n\\text{vectors},\\quad\n\\text{matrices},\\quad\n\\text{tensors},\\quad\n\\text{subspaces},\\quad\n\\text{graphs}.\n$$\n\n---\n\n# 28. Mathematician Mini-Biographies\n\n## 28.1 Seki Takakazu\n\n[Seki Takakazu](https://en.wikipedia.org/wiki/Seki_Takakazu) was a Japanese mathematician of the Edo period. He developed determinant ideas independently of European mathematicians.\n\nHis work shows that determinant theory did not belong to only one mathematical tradition.\n\n## 28.2 Gottfried Wilhelm Leibniz\n\n[Leibniz](https://en.wikipedia.org/wiki/Gottfried_Wilhelm_Leibniz) developed symbolic methods that anticipated determinant formulas. He is also famous for calculus and symbolic notation.\n\n## 28.3 Gabriel Cramer\n\n[Gabriel Cramer](https://en.wikipedia.org/wiki/Gabriel_Cramer) is remembered for Cramer's rule, which expresses solutions of linear systems using determinants.\n\n## 28.4 Carl Friedrich Gauss\n\n[Gauss](https://en.wikipedia.org/wiki/Carl_Friedrich_Gauss) contributed to elimination, least squares, number theory, geometry, statistics, and astronomy.\n\nIn linear algebra, his influence appears through:\n\n- Gaussian elimination,\n- least squares,\n- numerical computation,\n- quadratic forms.\n\n## 28.5 Joseph Fourier\n\n[Fourier](https://en.wikipedia.org/wiki/Joseph_Fourier) showed that functions could be decomposed into trigonometric waves.\n\nThis idea later became central to:\n\n- signal processing,\n- PDEs,\n- Hilbert spaces,\n- FFT.\n\n## 28.6 Hermann Grassmann\n\n[Grassmann](https://en.wikipedia.org/wiki/Hermann_Grassmann) developed a highly abstract theory of extension, including ideas close to vector spaces and exterior algebra.\n\nHis work was ahead of its time.\n\n## 28.7 James Joseph Sylvester\n\n[Sylvester](https://en.wikipedia.org/wiki/James_Joseph_Sylvester) introduced the word \"matrix\" and contributed to invariant theory and algebra.\n\n## 28.8 Arthur Cayley\n\n[Cayley](https://en.wikipedia.org/wiki/Arthur_Cayley) developed matrix algebra and treated matrices as mathematical objects.\n\n## 28.9 Camille Jordan\n\n[Jordan](https://en.wikipedia.org/wiki/Camille_Jordan) developed canonical forms that describe the structure of linear transformations.\n\n## 28.10 Ferdinand Georg Frobenius\n\n[Frobenius](https://en.wikipedia.org/wiki/Ferdinand_Georg_Frobenius) contributed deeply to matrix theory, group theory, and representation theory.\n\n## 28.11 David Hilbert\n\n[Hilbert](https://en.wikipedia.org/wiki/David_Hilbert) helped shape functional analysis and infinite-dimensional geometry.\n\n## 28.12 Issai Schur\n\n[Schur](https://en.wikipedia.org/wiki/Issai_Schur) introduced Schur decomposition, a central tool in matrix analysis.\n\n## 28.13 Alfréd Haar\n\n[Haar](https://en.wikipedia.org/wiki/Alfr%C3%A9d_Haar) introduced the Haar system, one of the earliest wavelet bases.\n\n## 28.14 John von Neumann\n\n[Von Neumann](https://en.wikipedia.org/wiki/John_von_Neumann) helped formulate quantum mechanics using Hilbert spaces and operators.\n\n## 28.15 Gene Golub\n\n[Gene Golub](https://en.wikipedia.org/wiki/Gene_H._Golub) was one of the founders of modern numerical linear algebra.\n\nHis work helped make matrix computations reliable and practical.\n\n---\n\n# 29. Python: Create a Timeline Plot\n\n::: {#88659c89 .cell execution_count=1}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\n\nevents = [\n    (\"Nine Chapters elimination\", -100),\n    (\"Seki determinants\", 1683),\n    (\"Leibniz determinants\", 1693),\n    (\"Cramer's rule\", 1750),\n    (\"Gauss least squares\", 1809),\n    (\"Fourier heat theory\", 1822),\n    (\"Hamilton quaternions\", 1843),\n    (\"Grassmann extension theory\", 1844),\n    (\"Sylvester names matrix\", 1848),\n    (\"Cayley matrix algebra\", 1858),\n    (\"Jordan canonical form\", 1870),\n    (\"Schur decomposition\", 1909),\n    (\"Haar basis\", 1910),\n    (\"Hilbert spaces\", 1920),\n    (\"Hotelling PCA\", 1933),\n    (\"Eckart-Young theorem\", 1936),\n    (\"QR algorithm\", 1961),\n    (\"FFT\", 1965),\n    (\"Wavelets\", 1988),\n    (\"PageRank\", 1998),\n    (\"Deep learning era\", 2012),\n]\n\nyears = [year for _, year in events]\nlabels = [label for label, _ in events]\n\nplt.figure(figsize=(14, 5))\nplt.axhline(0)\nplt.scatter(years, [0]*len(years))\n\nfor i, (label, year) in enumerate(events):\n    y = 0.35 if i % 2 == 0 else -0.45\n    plt.text(year, y, label, rotation=45, ha=\"right\", va=\"center\")\n\nplt.yticks([])\nplt.xlabel(\"Year\")\nplt.title(\"Historical Timeline of Major Linear Algebra Ideas\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](chapter-history-linear-algebra-timeline_files/figure-html/cell-2-output-1.png){width=1145 height=2846}\n:::\n:::\n\n\n---\n\n# 30. Practice Questions\n\n## Question 1\n\nWhy did determinants appear historically before matrices became formal objects?\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\nDeterminants were useful for solving systems of equations. Matrices were originally just coefficient tables. Only later did mathematicians such as Sylvester and Cayley treat matrices as objects with their own algebra.\n:::\n\n## Question 2\n\nExplain why Fourier analysis can be viewed as linear algebra.\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\nFourier analysis represents functions as sums of basis functions. Fourier coefficients are coordinates. Orthogonality and projection are the same ideas used in finite-dimensional inner product spaces.\n:::\n\n## Question 3\n\nWhy is Schur decomposition more useful than Jordan form in numerical computation?\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\nJordan form is very sensitive to perturbations and is often numerically unstable. Schur decomposition uses unitary transformations, which preserve length and are stable in floating-point computation.\n:::\n\n## Question 4\n\nWhy is SVD especially important for data science?\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\nSVD applies to every matrix, including rectangular data matrices. It gives low-rank approximations, principal directions, compression, denoising, pseudoinverses, and PCA.\n:::\n\n## Question 5\n\nWhat is the difference between Fourier and Haar bases?\n\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\nFourier bases are global waves and are excellent for frequency information. Haar bases are localized and multiscale, making them useful for detecting local changes and compressing signals with sharp features.\n:::\n\n---\n\n# 31. AI Companion Activities\n\n## Activity 1: Historical Concept Map\n\nAsk an AI tool:\n\n> Create a concept map connecting determinants, matrices, vector spaces, eigenvalues, Fourier analysis, Hilbert spaces, SVD, QR algorithm, FFT, PCA, and AI.\n\nThen compare the answer with this chapter.\n\n## Activity 2: Mathematician Biography\n\nChoose one mathematician from this chapter and ask:\n\n> Explain this mathematician's contribution to linear algebra in three levels: high school, undergraduate, and graduate.\n\n## Activity 3: Timeline Reconstruction\n\nAsk:\n\n> Make a timeline of linear algebra from ancient elimination to deep learning, including years and mathematicians.\n\nThen check whether it includes:\n\n- Seki,\n- Leibniz,\n- Cramer,\n- Gauss,\n- Fourier,\n- Grassmann,\n- Sylvester,\n- Cayley,\n- Jordan,\n- Frobenius,\n- Hilbert,\n- Schur,\n- Haar,\n- Golub.\n\n## Activity 4: Historical Reflection\n\nAsk:\n\n> Why did numerical linear algebra become so important after computers were invented?\n\nThen write a short answer connecting stability, complexity, and large data matrices.\n\n---\n\n# 32. Key Takeaways\n\n1. Linear algebra began with systems of equations.\n2. Determinants were developed before matrices were formalized.\n3. Matrices became mathematical objects through Sylvester and Cayley.\n4. Grassmann's abstract vector ideas became central only later.\n5. Fourier analysis extended linear algebra to functions.\n6. Hilbert spaces made infinite-dimensional geometry rigorous.\n7. Eigenvalues describe hidden directions of transformations.\n8. Symmetric matrices led to the spectral theorem.\n9. Schur decomposition provides stable triangularization.\n10. SVD became the universal decomposition for data matrices.\n11. Haar bases and wavelets introduced multiscale linear algebra.\n12. Numerical linear algebra transformed the subject into a computational science.\n13. Modern AI depends on vectors, matrices, tensors, optimization, and decompositions.\n\n---\n\n# 33. Closing Reflection\n\nThe history of linear algebra is a story of both abstraction and usefulness.\n\nEach abstraction made the subject more powerful:\n\n$$\n\\text{numbers}\n\\rightarrow\n\\text{vectors}\n\\rightarrow\n\\text{matrices}\n\\rightarrow\n\\text{spaces}\n\\rightarrow\n\\text{operators}\n\\rightarrow\n\\text{algorithms}\n\\rightarrow\n\\text{data}.\n$$\n\nLinear algebra is not only a branch of mathematics. It is one of the main languages of modern science, computation, and artificial intelligence.\n\n---\n\n# 34. Selected Wikipedia Links for Further Reading\n\n- [Linear algebra](https://en.wikipedia.org/wiki/Linear_algebra)\n- [Timeline of mathematics](https://en.wikipedia.org/wiki/Timeline_of_mathematics)\n- [Timeline of algebra](https://en.wikipedia.org/wiki/Timeline_of_algebra)\n- [Matrix mathematics](https://en.wikipedia.org/wiki/Matrix_(mathematics))\n- [Determinant](https://en.wikipedia.org/wiki/Determinant)\n- [Gaussian elimination](https://en.wikipedia.org/wiki/Gaussian_elimination)\n- [Vector space](https://en.wikipedia.org/wiki/Vector_space)\n- [Eigenvalues and eigenvectors](https://en.wikipedia.org/wiki/Eigenvalues_and_eigenvectors)\n- [Spectral theorem](https://en.wikipedia.org/wiki/Spectral_theorem)\n- [Schur decomposition](https://en.wikipedia.org/wiki/Schur_decomposition)\n- [Singular value decomposition](https://en.wikipedia.org/wiki/Singular_value_decomposition)\n- [Fourier series](https://en.wikipedia.org/wiki/Fourier_series)\n- [Fourier transform](https://en.wikipedia.org/wiki/Fourier_transform)\n- [Fast Fourier transform](https://en.wikipedia.org/wiki/Fast_Fourier_transform)\n- [Haar wavelet](https://en.wikipedia.org/wiki/Haar_wavelet)\n- [Hilbert space](https://en.wikipedia.org/wiki/Hilbert_space)\n- [Grassmannian](https://en.wikipedia.org/wiki/Grassmannian)\n- [Tensor](https://en.wikipedia.org/wiki/Tensor)\n- [Principal component analysis](https://en.wikipedia.org/wiki/Principal_component_analysis)\n- [Numerical linear algebra](https://en.wikipedia.org/wiki/Numerical_linear_algebra)\n- [PageRank](https://en.wikipedia.org/wiki/PageRank)\n- [Deep learning](https://en.wikipedia.org/wiki/Deep_learning)\n\n",
    "supporting": [
      "chapter-history-linear-algebra-timeline_files"
    ],
    "filters": [],
    "includes": {}
  }
}